### PR TITLE
Field Type: Add 'textarea' field type

### PR DESCRIPTION
**Pull request by earboxer**
Updated this. The first commit includes my changes (you can cherry-pick this if you want).

The second commit is the result after running `npm run dev`. (It still seems a little weird to me that we're committing compiled files... probably there isn't much that can be helped here?)

### CODE REVIEW

**Comment by earboxer** [comment]
(as discussed in https://github.com/poowf/otter/issues/17)

**Comment by zanechua** [comment]
Just took a look at your PR, when you made this PR did you rebase the current develop? You are making modifications to some of the changes that aren't meant to be changed e.g. the pathPrefix is supposed to be there.

If could rebase to the latest develop that would be good and remove all published assets. The spacing in FormComponent.vue is off also and can't clearly see what you modified. 

Probably should add a linter of some sort.

**Comment by earboxer** [comment]
hmm didn't realize that about FormComponent.vue (I think it might have something to do with line endings). I've removed the commit with the compiled assets. I'll try to fix it up so it includes only the changes I wrote (I don't remember changing `${this.pathPrefix}`)...

**Comment by earboxer** [comment]
Okay, I've merged in the latest changes. Looks like you've already incorporated the major functional things, so the only things left are stylistic. :)

I'm not set up right now to test things right now, so you can decide if it seems good/if these changes are still necessary.

**Comment by zanechua** [comment]
Yeah. Was intending to do the wysiwyg editor since I knew that wouldn't take long and ended up making the changes for textarea too. Will merge this in for the stylisation. Just need to make two minor edits.

**Comment by zanechua** [comment]
I'm.. coming back to this again after a long while. 2019 has been a busy year. On that note. I totally do not remember what changes I was supposed to make... So I'm just going to merge this seeing as it is just styling updates.

**Pull request merged**
